// Generated by Google AI
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.Rendering.RenderGraphModule;

public class GrayscaleFeature : ScriptableRendererFeature
{
    [SerializeField] private Material m_Material;
    private GrayscalePass m_Pass;

    public override void Create()
    {
        m_Pass = new GrayscalePass(m_Material);
        m_Pass.renderPassEvent = RenderPassEvent.AfterRenderingPostProcessing;
    }

    public override void AddRenderPasses(ScriptableRenderer renderer, ref RenderingData renderingData)
    {
        if (m_Material != null)
            renderer.EnqueuePass(m_Pass);
    }

    private class GrayscalePass : ScriptableRenderPass
    {
        private Material m_Material;

        public GrayscalePass(Material mat) => m_Material = mat;

        private class PassData
        {
            public TextureHandle src;
        }

        public override void RecordRenderGraph(RenderGraph renderGraph, ContextContainer frameData)
        {
            var resourceData = frameData.Get<UniversalResourceData>();
            if (!resourceData.activeColorTexture.IsValid()) return;

            // 1. descripting temporary texture
            var desc = renderGraph.GetTextureDesc(resourceData.activeColorTexture);
            desc.name = "TempColorBuffer";
            TextureHandle tempTexture = renderGraph.CreateTexture(desc);

            // 2. FIRST PASS: Copy screen tex into temp tex
            using (var builder = renderGraph.AddRasterRenderPass<PassData>("Copy Screen Pass", out var passData))
            {
                passData.src = resourceData.activeColorTexture;
                builder.UseTexture(passData.src, AccessFlags.Read);
                builder.SetRenderAttachment(tempTexture, 0);

                builder.SetRenderFunc((PassData data, RasterGraphContext context) =>
                {
                    // Simple copy without material
                    Blitter.BlitTexture(context.cmd, data.src, new Vector4(1, 1, 0, 0), 0, false);
                });
            }

            // 3. SECOND PASS: Drawing from temp tex into main one with effect
            using (var builder = renderGraph.AddRasterRenderPass<PassData>("Grayscale Effect Pass", out var passData))
            {
                passData.src = tempTexture;
                builder.UseTexture(passData.src, AccessFlags.Read);
                builder.SetRenderAttachment(resourceData.activeColorTexture, 0);

                builder.SetRenderFunc((PassData data, RasterGraphContext context) =>
                {
                    // Applying grayscale material
                    // Texture name MUST be _BlitTexture
                    Blitter.BlitTexture(context.cmd, data.src, new Vector4(1, 1, 0, 0), m_Material, 0);
                });
            }
        }
    }
}
